Repository grafana/mimir, pull requests merged in 2025-10, with the labels that each got.

#12866 Revert moving dashboard links into config
  operations/mimir-mixin/config.libsonnet
  operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
Labels: changelog-not-needed

#12868 Remote execution: don't mark trace spans as failed if request is cancelled
  pkg/frontend/querymiddleware/limits.go
  pkg/querier/dispatcher.go
Labels: changelog-not-needed

#12870 Remote execution: don't panic if stream ends unexpectedly
  CHANGELOG.md
  pkg/frontend/v2/remoteexec.go
Labels: backport r362

#12877 parquet converter: test and refactor block conversion skip logic
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  cmd/mimir/help.txt.tmpl
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/parquetconverter/parquet_converter.go
  pkg/parquetconverter/parquet_converter_test.go
Labels: changelog-not-needed

#12792 mimirpb: Refactor RW2 metadata handling out of generated code
  pkg/mimirpb/compat_rw2_test.go
  pkg/mimirpb/custom.go
  pkg/mimirpb/mimir.pb.go
  pkg/mimirpb/mimir.pb.go.expdiff
  pkg/mimirpb/timeseries.go
Labels: component/ingester, changelog-not-needed

#12892 fix(parquet store gateway): map limit errors to UnprocessableEntity status
  pkg/storegateway/parquet_bucket_store.go
  pkg/storegateway/parquet_bucket_store_test.go
Labels: changelog-not-needed

#12908 [r362] Fix issue where binary expressions with one side containing parentheses aren't sharded
  pkg/frontend/querymiddleware/astmapper/sharding.go
  pkg/frontend/querymiddleware/astmapper/sharding_test.go
  pkg/frontend/querymiddleware/querysharding.go
Labels: backport

#12921 Fix more issues where some binary expressions aren't sharded
  pkg/frontend/querymiddleware/astmapper/sharding.go
  pkg/frontend/querymiddleware/astmapper/sharding_test.go
Labels: changelog-not-needed, backport r362, backport r363

#12928 [r362] Fix more issues where some binary expressions aren't sharded
  pkg/frontend/querymiddleware/astmapper/sharding.go
  pkg/frontend/querymiddleware/astmapper/sharding_test.go
Labels: backport

#12926 Add AGENT.md for docs ai
  AGENTS.md
Labels: type/docs, changelog-not-needed

#12922 parquet-converter: best-effort distributed locking for blocks load balancing
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  cmd/mimir/help.txt.tmpl
  docs/sources/mimir/configure/configuration-parameters/index.md
  operations/mimir/mimir-flags-defaults.json
  pkg/parquetconverter/load_balancer.go
  pkg/parquetconverter/metrics.go
  pkg/parquetconverter/parquet_converter.go
  pkg/parquetconverter/parquet_converter_ring_test.go
  pkg/parquetconverter/parquet_converter_test.go
Labels: changelog-not-needed

#12749 docs: document ingest storage jsonnet setup
  docs/sources/mimir/set-up/jsonnet/configure-ingest-storage.md
Labels: changelog-not-needed

#12830 lookup planning: adjust plan's intersection cost
  pkg/ingester/lookupplan/mock_statistics_test.go
  pkg/ingester/lookupplan/plan.go
  pkg/ingester/lookupplan/plan_test.go
  pkg/ingester/lookupplan/planner_test.go
  pkg/ingester/lookupplan/stats_test.go
  pkg/ingester/lookupplan/testdata/plan_cost_test_cases.csv
  pkg/ingester/lookupplan/testdata/planner_test_cases.csv
Labels: changelog-not-needed

#12932 Build postings cache factories per ingester
  pkg/ingester/ingester.go
Labels: changelog-not-needed

#12941 parquet-converter: add logs on enqueue
  pkg/parquetconverter/parquet_converter.go
Labels: changelog-not-needed
