Repository grafana/mimir, pull requests merged in 2025-08, with the labels that each got.

#12266 revert #11889 and fix conflicts.
  CHANGELOG.md
  pkg/distributor/errors.go
  pkg/distributor/otel.go
  pkg/distributor/otel_test.go
  pkg/distributor/validate.go
  pkg/distributor/validate_test.go
Labels: changelog-not-needed

#12268 MQE: reduce numerical errors by not inlining `KahanSumInc`
  pkg/streamingpromql/floats/kahan.go
Labels: changelog-not-needed

#12238 Pass ctx to Map and MapExpr for ASTMapper
  pkg/frontend/querymiddleware/astmapper/astmapper.go
  pkg/frontend/querymiddleware/astmapper/astmapper_test.go
  pkg/frontend/querymiddleware/astmapper/prom2_range_compat.go
  pkg/frontend/querymiddleware/astmapper/prom2_range_compat_test.go
  pkg/frontend/querymiddleware/astmapper/pruning.go
  pkg/frontend/querymiddleware/astmapper/pruning_test.go
  pkg/frontend/querymiddleware/astmapper/sharding.go
  pkg/frontend/querymiddleware/astmapper/sharding_test.go
  pkg/frontend/querymiddleware/astmapper/subquery_spin_off.go
  pkg/frontend/querymiddleware/astmapper/subquery_spin_off_test.go
  pkg/frontend/querymiddleware/astmapper/subtree_folder.go
  pkg/frontend/querymiddleware/astmapper/subtree_folder_test.go
  pkg/frontend/querymiddleware/prom2_range_compat.go
  pkg/frontend/querymiddleware/prune.go
  pkg/frontend/querymiddleware/querysharding.go
  pkg/frontend/querymiddleware/spin_off_subqueries.go
Labels: changelog-not-needed

#11964 [HELM] Add labels configuration for gateway ingress
  operations/helm/charts/mimir-distributed/CHANGELOG.md
  operations/helm/charts/mimir-distributed/ci/offline/test-enterprise-values.yaml
  operations/helm/charts/mimir-distributed/templates/gateway/gateway-ingress.yaml
  operations/helm/charts/mimir-distributed/values.yaml
  operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/gateway/gateway-ingress.yaml
Labels: release/notified-changelog-cut

#12276 chore: Fix configuration setting used in query-frontend error
  pkg/mimir/modules.go
Labels: changelog-not-needed

#12275 Backporting #12266 to release 2.17
  CHANGELOG.md
  pkg/distributor/errors.go
  pkg/distributor/otel.go
  pkg/distributor/otel_test.go
  pkg/distributor/validate.go
  pkg/distributor/validate_test.go
Labels: changelog-not-needed

#12188 helm: Make query-scheduler a required component
  operations/helm/charts/mimir-distributed/CHANGELOG.md
  operations/helm/charts/mimir-distributed/templates/query-frontend/query-frontend-svc-headless.yaml
  operations/helm/charts/mimir-distributed/values.yaml
Labels: helm, release/notified-changelog-cut

#12117 Parallelize `updateBlock`
  CHANGELOG.md
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/storage/tsdb/bucketindex/storage_test.go
  pkg/storage/tsdb/bucketindex/updater.go
  pkg/storage/tsdb/bucketindex/updater_test.go
  pkg/storegateway/gateway_test.go
  pkg/storegateway/metadata_fetcher_filters_test.go
Labels: release/notified-changelog-cut

#12250 mimir-distributed 5.8 release notes
  docs/sources/helm-charts/mimir-distributed/release-notes/v5.8.md
Labels: type/docs, changelog-not-needed

#12289 Alertmanager: Refactor createUsableGrafanaConfig
  pkg/alertmanager/api_grafana.go
  pkg/alertmanager/config.go
  pkg/alertmanager/config_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: changelog-not-needed

#12306 Distributor: Introduce OTel translation strategy
  CHANGELOG.md
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  docs/sources/mimir/configure/about-versioning.md
  docs/sources/mimir/configure/configuration-parameters/index.md
  integration/otlp_ingestion_test.go
  pkg/distributor/otel.go
  pkg/distributor/otel_test.go
  pkg/distributor/push_test.go
  pkg/mimir/mimir.go
  pkg/mimir/mimir_test.go
  pkg/mimir/runtime_config.go
  pkg/mimir/runtime_config_test.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_mock.go
  pkg/util/validation/limits_test.go
  pkg/util/validation/otel_translation_strategy.go
  pkg/util/validation/otel_translation_strategy_test.go
Labels: enhancement, component/distributor, area/opentelemetry

#12319 mimir-mixin: relax the guard in IngesterHasUnshippedBlocks when block-builder is running
  operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
  operations/mimir-mixin-compiled-baremetal/alerts.yaml
  operations/mimir-mixin-compiled-gem/alerts.yaml
  operations/mimir-mixin-compiled/alerts.yaml
  operations/mimir-mixin/alerts/blocks.libsonnet
Labels: changelog-not-needed

#12271 Warn about unsafe mutable labels in type names and doc strings
  pkg/distributor/validate.go
  pkg/mimirpb/mimir.pb.go
  pkg/mimirpb/mimir.pb.go.expdiff
  pkg/mimirpb/mimir.proto
  pkg/mimirpb/timeseries.go
Labels: changelog-not-needed

#12320 Trigger request buffer reuse in distributor validation tests
  pkg/api/api.go
  pkg/costattribution/testutils/test_utils.go
  pkg/distributor/distributor_test.go
  pkg/distributor/push.go
  pkg/distributor/push_test.go
  pkg/distributor/validate_test.go
  pkg/util/active_groups.go
  pkg/util/requestbuffers.go
Labels: changelog-not-needed

#12255 Alertmanager: Use the current configuration to start per-tenant Alermanagers after a request
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: changelog-not-needed

#12330 Parquet SG: Finally correct shard reader lifecycle
  cmd/mimir/help-all.txt.tmpl
  development/mimir-microservices-mode/docker-compose.jsonnet
  go.mod
  go.sum
  pkg/parquetconverter/parquet_converter.go
  pkg/storage/parquet/block/lazy_reader.go
  pkg/storage/parquet/block/reader.go
  pkg/storegateway/parquet_bucket_block.go
  pkg/storegateway/parquet_bucket_store.go
  vendor/github.com/prometheus-community/parquet-common/convert/convert.go
  vendor/github.com/prometheus-community/parquet-common/queryable/parquet_queryable.go
  vendor/github.com/prometheus-community/parquet-common/schema/encoder.go
  vendor/github.com/prometheus-community/parquet-common/schema/schema_builder.go
  vendor/github.com/prometheus-community/parquet-common/search/constraint.go
  vendor/github.com/prometheus-community/parquet-common/search/materialize.go
  vendor/github.com/prometheus-community/parquet-common/storage/parquet_shard.go
  vendor/github.com/prometheus-community/parquet-common/util/bitmap.go
  vendor/modules.txt
Labels: changelog-not-needed

#12185 PromQL: Fix invalid source label name in label_join error message
  pkg/streamingpromql/operators/functions/label.go
  pkg/streamingpromql/testdata/ours/functions.test
Labels: bug, component/querier, changelog-not-needed

#12338 Document yoloStrings and buffer pooling in contributing/README.md
  docs/internal/contributing/README.md
Labels: changelog-not-needed

#12369 Distributor: Auto-deduce OTel translation strategy in OTLP endpoint if unset
  CHANGELOG.md
  pkg/distributor/otel_test.go
  pkg/mimir/runtime_config_test.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_mock.go
  pkg/util/validation/limits_test.go
Labels: bug, component/distributor, area/opentelemetry, backport r355

#12343 Add new intro topic
  docs/sources/mimir/_index.md
  docs/sources/mimir/introduction/_index.md
Labels: type/docs, changelog-not-needed

#12363 Upgrade dskit
  go.mod
  go.sum
  vendor/github.com/grafana/dskit/tracing/otel.go
  vendor/github.com/grafana/dskit/tracing/otel_jaeger.go
  vendor/modules.txt
Labels: changelog-not-needed

#12366 Alertmanager: Add HTTP tracing to notify hooks outgoing requests
  pkg/alertmanager/notify_hooks_notifier.go
Labels: changelog-not-needed

#12385 docs: DNS service discovery domains must be fully qualified
  CHANGELOG.md
  docs/sources/mimir/configure/about-dns-service-discovery.md
Labels: type/docs

#12377 MQE: shift responsibilities of `Materializer`
  pkg/streamingpromql/engine.go
  pkg/streamingpromql/materialize.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/node.go
  pkg/streamingpromql/planning/core/aggregate_expression.go
  pkg/streamingpromql/planning/core/binary_expression.go
  pkg/streamingpromql/planning/core/function_call.go
  pkg/streamingpromql/planning/core/matrix_selector.go
  pkg/streamingpromql/planning/core/number_literal.go
  pkg/streamingpromql/planning/core/string_literal.go
  pkg/streamingpromql/planning/core/subquery.go
  pkg/streamingpromql/planning/core/unary_expression.go
  pkg/streamingpromql/planning/core/vector_selector.go
  pkg/streamingpromql/planning/materialize.go
  pkg/streamingpromql/planning/plan.go
  pkg/streamingpromql/planning/plan_test.go
Labels: changelog-not-needed

#12302 Remote execution of query plans in queriers
  pkg/api/api.go
  pkg/api/handlers.go
  pkg/frontend/v2/frontend_scheduler_adapter.go
  pkg/frontend/v2/frontendv2pb/frontend.pb.go
  pkg/frontend/v2/frontendv2pb/frontend.proto
  pkg/frontend/v2/frontendv2pb/writer.go
  pkg/mimir/mimir.go
  pkg/mimir/modules.go
  pkg/querier/dispatcher.go
  pkg/querier/dispatcher_test.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/querier/querierpb/querier.pb.go
  pkg/querier/querierpb/querier.proto
  pkg/querier/worker/scheduler_processor.go
  pkg/querier/worker/scheduler_processor_test.go
  pkg/querier/worker/worker.go
  pkg/scheduler/queue/queue.go
  pkg/scheduler/queue/queue_broker_test.go
  pkg/scheduler/queue/queue_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/scheduler/schedulerpb/scheduler.pb.go
  pkg/scheduler/schedulerpb/scheduler.proto
  pkg/streamingpromql/engine.go
  pkg/streamingpromql/evaluator.go
  pkg/streamingpromql/planning/plan.go
  pkg/streamingpromql/planning_test.go
  pkg/streamingpromql/query.go
  tools/evaluate-query-plan/main.go
Labels: changelog-not-needed

#12393 vendor parquet-common at 3e7764e with sparse data skip
  go.mod
  go.sum
  vendor/github.com/prometheus-community/parquet-common/search/iterators.go
  vendor/modules.txt
Labels: changelog-not-needed

#12394 MQE: query-frontend refactoring to support remote execution of query plans in queriers
  pkg/frontend/v2/frontend.go
  pkg/frontend/v2/frontend_scheduler_adapter.go
  pkg/frontend/v2/frontend_scheduler_adapter_test.go
Labels: changelog-not-needed

#12396 MQE: add the ability to compute the queried time range for a query plan node
  pkg/streamingpromql/operators/selectors/selector.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/node.go
  pkg/streamingpromql/planning/core/aggregate_expression.go
  pkg/streamingpromql/planning/core/binary_expression.go
  pkg/streamingpromql/planning/core/function_call.go
  pkg/streamingpromql/planning/core/matrix_selector.go
  pkg/streamingpromql/planning/core/matrix_selector_test.go
  pkg/streamingpromql/planning/core/number_literal.go
  pkg/streamingpromql/planning/core/string_literal.go
  pkg/streamingpromql/planning/core/subquery.go
  pkg/streamingpromql/planning/core/unary_expression.go
  pkg/streamingpromql/planning/core/vector_selector.go
  pkg/streamingpromql/planning/core/vector_selector_test.go
  pkg/streamingpromql/planning/plan.go
  pkg/streamingpromql/planning/plan_test.go
Labels: changelog-not-needed

#12415 Multiple Components: Include vector(0) in Memory HPA Metric
  operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
  operations/mimir-tests/test-autoscaling-generated.yaml
  operations/mimir-tests/test-multi-zone-distributor-generated.yaml
  operations/mimir-tests/test-new-resource-scaled-object-generated.yaml
  operations/mimir-tests/test-single-to-multi-zone-distributor-migration-generated.yaml
  operations/mimir/autoscaling.libsonnet
Labels: changelog-not-needed

#12410 MQE: introduce `Node.ExpressionPosition()` method
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/node.go
  pkg/streamingpromql/planning/core/aggregate_expression.go
  pkg/streamingpromql/planning/core/binary_expression.go
  pkg/streamingpromql/planning/core/function_call.go
  pkg/streamingpromql/planning/core/matrix_selector.go
  pkg/streamingpromql/planning/core/number_literal.go
  pkg/streamingpromql/planning/core/string_literal.go
  pkg/streamingpromql/planning/core/subquery.go
  pkg/streamingpromql/planning/core/unary_expression.go
  pkg/streamingpromql/planning/core/vector_selector.go
  pkg/streamingpromql/planning/plan.go
  pkg/streamingpromql/planning/plan_test.go
Labels: changelog-not-needed

#12436 Vendor dskit
  go.mod
  go.sum
  vendor/github.com/grafana/dskit/grpcutil/taphandle.go
  vendor/github.com/grafana/dskit/ring/replication_set.go
  vendor/github.com/grafana/dskit/server/server.go
  vendor/modules.txt
Labels: dependency-update

#12413 chore: Remove release-2.15 from automated updates
  renovate.json5
Labels: changelog-not-needed

#12438 MQE: don't panic if remote execution attempted on querier with MQE disabled
  pkg/querier/dispatcher.go
  pkg/querier/dispatcher_test.go
Labels: changelog-not-needed

#12437 Replace StringsContain with slices.Contains.
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/frontend/querymiddleware/querysharding_test.go
  pkg/frontend/querymiddleware/results_cache.go
  pkg/frontend/querymiddleware/sharded_queryable.go
  pkg/mimir/mimir.go
  pkg/mimir/modules.go
  pkg/querier/blocks_store_replicated_set.go
  pkg/scheduler/schedulerdiscovery/config.go
  pkg/storage/bucket/client.go
  pkg/storage/bucket/s3/config.go
  pkg/storage/tsdb/index_cache.go
  pkg/storegateway/bucket_stores_test.go
  pkg/usagestats/reporter.go
  pkg/util/strings.go
  pkg/util/validation/limits.go
  pkg/util/validation/notifications_limit_flag.go
Labels: changelog-not-needed

#12324 docs: draft topic for mimir query best practices
  docs/sources/mimir/query/query-best-practices.md
Labels: type/docs, changelog-not-needed

#12121 10638 - Fuzz tests for MQE
  go.mod
  go.sum
  pkg/streamingpromql/README_FUZZ_TESTING.md
  pkg/streamingpromql/engine_fuzz_test.go
  pkg/streamingpromql/testdata/fuzz/data/seed-data.test
  pkg/streamingpromql/testdata/fuzz/data/seed-queries.test
  pkg/streamingpromql/testutils/compat_fixup_labels_slice.go
  pkg/streamingpromql/testutils/compat_fixup_labels_stringlabels.go
  pkg/streamingpromql/testutils/utils.go
  tools/promql-generator/README.md
  tools/promql-generator/promql-generator.go
  tools/promql-generator/sample_series.json
  vendor/github.com/cortexproject/promqlsmith/.gitignore
  vendor/github.com/cortexproject/promqlsmith/.go-version
  vendor/github.com/cortexproject/promqlsmith/.golangci.yml
  vendor/github.com/cortexproject/promqlsmith/LICENSE
  vendor/github.com/cortexproject/promqlsmith/Makefile
  vendor/github.com/cortexproject/promqlsmith/README.md
  vendor/github.com/cortexproject/promqlsmith/opts.go
  vendor/github.com/cortexproject/promqlsmith/promqlsmith.go
  vendor/github.com/cortexproject/promqlsmith/walk.go
  vendor/modules.txt
Labels: changelog-not-needed

#12450 Alertmanager: Fix computeConfig warning log
  pkg/alertmanager/multitenant.go
Labels: changelog-not-needed

#12446 [mimir-distributed-release-5.8] Update image versions, changelog, release notes for final release
  docs/sources/helm-charts/mimir-distributed/release-notes/v5.8.md
  operations/helm/charts/mimir-distributed/CHANGELOG.md
  operations/helm/charts/mimir-distributed/Chart.yaml
  operations/helm/charts/mimir-distributed/README.md
  operations/helm/charts/mimir-distributed/values.yaml
Labels: changelog-not-needed

#12455 Merge distributed release 5.8 to main
  operations/helm/charts/mimir-distributed/CHANGELOG.md
Labels: changelog-not-needed

#12405 enable in-order store-gateway replica load balancing for parquet
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  development/mimir-microservices-mode/config/mimir.yaml
  development/mimir-microservices-mode/docker-compose.jsonnet
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_replicated_set.go
  pkg/querier/blocks_store_replicated_set_test.go
  pkg/querier/querier.go
Labels: changelog-not-needed

#12449 MQE: separate query planner for querier and query-frontends
  pkg/mimir/mimir.go
  pkg/mimir/mimir_test.go
  pkg/mimir/modules.go
  pkg/mimir/sanity_check.go
Labels: changelog-not-needed

#12461 rw2: Do not silently drop metric metadata of type Unknown
  CHANGELOG.md
  pkg/mimirpb/compat_rw2_test.go
  pkg/mimirpb/mimir.pb.go
  pkg/mimirpb/mimir.pb.go.expdiff
  pkg/mimirpb/prealloc_rw2_test.go
Labels: bug, component/distributor

#12463 Update publish-technical-documentation-release-helm-charts.yml to lat…
  .github/workflows/publish-technical-documentation-release-helm-charts.yml
Labels: changelog-not-needed

#12465 Alerting: Update alerting module to e93687a58b
  go.mod
  go.sum
  vendor/github.com/grafana/alerting/receivers/jira/jira.go
  vendor/github.com/grafana/alerting/receivers/jira/types.go
  vendor/modules.txt
Labels: component/alertmanager, changelog-not-needed, backport r355

#12468 [r356] Alerting: Update alerting module to e93687a58b
  go.mod
  go.sum
  vendor/github.com/grafana/alerting/receivers/jira/jira.go
  vendor/github.com/grafana/alerting/receivers/jira/types.go
  vendor/modules.txt
Labels: backport, changelog-not-needed

#12473 MQE: Improve fuzz tests erorr messages
  pkg/streamingpromql/engine_fuzz_test.go
Labels: changelog-not-needed

#12496 Upgrade to latest prometheus/client_golang
  go.mod
  go.sum
  integration/e2emimir/client.go
  integration/getting_started_with_grafana_mimir_test.go
  integration/influx_ingestion_test.go
  integration/otlp_ingestion_test.go
  integration/querier_test.go
  integration/query_frontend_labels_query_optimizer_test.go
  integration/read_write_mode_test.go
  vendor/github.com/grafana/e2e/service.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/go_runtime_metrics.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/push/push.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/fuzz.go
  vendor/github.com/prometheus/common/expfmt/text_parse.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/modules.txt
Labels: chore, changelog-not-needed

#12492 MQE: introduce `Finalize` method to operators
  pkg/streamingpromql/evaluator.go
  pkg/streamingpromql/operators/aggregations/aggregation.go
  pkg/streamingpromql/operators/aggregations/count_values.go
  pkg/streamingpromql/operators/aggregations/quantile.go
  pkg/streamingpromql/operators/aggregations/topkbottomk/instant_query.go
  pkg/streamingpromql/operators/aggregations/topkbottomk/range_query.go
  pkg/streamingpromql/operators/binops/and_unless_binary_operation.go
  pkg/streamingpromql/operators/binops/and_unless_binary_operation_test.go
  pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation.go
  pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation_test.go
  pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation.go
  pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation_test.go
  pkg/streamingpromql/operators/binops/or_binary_operation.go
  pkg/streamingpromql/operators/binops/or_binary_operation_test.go
  pkg/streamingpromql/operators/binops/scalar_scalar_binary_operation.go
  pkg/streamingpromql/operators/binops/vector_scalar_binary_operation.go
  pkg/streamingpromql/operators/deduplicate_and_merge.go
  pkg/streamingpromql/operators/functions/absent.go
  pkg/streamingpromql/operators/functions/absent_over_time.go
  pkg/streamingpromql/operators/functions/function_over_instant_vector.go
  pkg/streamingpromql/operators/functions/function_over_instant_vector_test.go
  pkg/streamingpromql/operators/functions/function_over_range_vector.go
  pkg/streamingpromql/operators/functions/histogram_function.go
  pkg/streamingpromql/operators/functions/sort.go
  pkg/streamingpromql/operators/functions/sort_by_label.go
  pkg/streamingpromql/operators/operator_buffer.go
  pkg/streamingpromql/operators/operator_buffer_test.go
  pkg/streamingpromql/operators/scalars/instant_vector_to_scalar.go
  pkg/streamingpromql/operators/scalars/scalar_constant.go
  pkg/streamingpromql/operators/scalars/scalar_to_instant_vector.go
  pkg/streamingpromql/operators/scalars/unary_negation_scalar.go
  pkg/streamingpromql/operators/selectors/instant_vector_selector.go
  pkg/streamingpromql/operators/selectors/range_vector_selector.go
  pkg/streamingpromql/operators/string.go
  pkg/streamingpromql/operators/subquery.go
  pkg/streamingpromql/operators/test_operator.go
  pkg/streamingpromql/operators/time.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/instant_vector_operator.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/instant_vector_operator_test.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/range_vector_operator.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/range_vector_operator_test.go
  pkg/streamingpromql/types/operator.go
Labels: changelog-not-needed

#12470 MQE: Move DeduplicateAndMerge to planning stage
  pkg/querier/dispatcher_test.go
  pkg/streamingpromql/engine.go
  pkg/streamingpromql/operators/binops/or_binary_operation.go
  pkg/streamingpromql/operators/binops/or_binary_operation_test.go
  pkg/streamingpromql/operators/functions/common.go
  pkg/streamingpromql/operators/functions/factories.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass_test.go
  pkg/streamingpromql/optimize/plan/skip_histogram_decoding_test.go
  pkg/streamingpromql/planning.go
  pkg/streamingpromql/planning/core/binary_expression.go
  pkg/streamingpromql/planning/core/core.go
  pkg/streamingpromql/planning/core/core.pb.go
  pkg/streamingpromql/planning/core/core.proto
  pkg/streamingpromql/planning/core/deduplicate_and_merge.go
  pkg/streamingpromql/planning/plan.pb.go
  pkg/streamingpromql/planning/plan.proto
  pkg/streamingpromql/planning_test.go
Labels: changelog-not-needed

#12493 docs: update run-in-production following the deprecation of chart's meta-monitoring
  docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
Labels: changelog-not-needed

#12481 Alertmanager: Add ExtraData field to experimental pre-notification hook
  pkg/alertmanager/notify_hooks_notifier.go
  pkg/alertmanager/notify_hooks_notifier_test.go
Labels: changelog-not-needed

#12443 blockbuilder: reuse ingester-storage pusher consumer
  pkg/blockbuilder/blockbuilder.go
  pkg/blockbuilder/blockbuilder_test.go
  pkg/blockbuilder/tsdb.go
  pkg/blockbuilder/tsdb_test.go
  pkg/storage/ingest/pusher.go
  pkg/storage/ingest/pusher_metrics.go
  pkg/storage/ingest/pusher_test.go
  pkg/storage/ingest/reader.go
  pkg/storage/ingest/reader_test.go
Labels: changelog-not-needed

#12466 Parquet streaming poc
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  docs/sources/mimir/configure/configuration-parameters/index.md
  go.mod
  go.sum
  pkg/parquetconverter/priority_queue_test.go
  pkg/querier/batch/merge.go
  pkg/querier/block_streaming.go
  pkg/storage/parquet/chunk_querier.go
  pkg/storage/parquet/iterators.go
  pkg/storage/parquet/queryable_shard.go
  pkg/storage/parquet/queryable_shard_test.go
  pkg/storage/tsdb/config.go
  pkg/storegateway/parquet_bucket_store.go
  pkg/storegateway/parquet_bucket_store_test.go
  pkg/storegateway/parquet_bucket_stores.go
  vendor/github.com/prometheus-community/parquet-common/queryable/parquet_queryable.go
  vendor/github.com/prometheus-community/parquet-common/search/materialize.go
  vendor/modules.txt
Labels: changelog-not-needed

#12512 MQE: don't ignore error in `RangeVectorSelector.fillBuffer`
  pkg/streamingpromql/operators/selectors/range_vector_selector.go
Labels: changelog-not-needed

#12513 MQE: add context parameter to `RangeVectorOperator.NextStepSamples`
  pkg/streamingpromql/evaluator.go
  pkg/streamingpromql/operators/functions/absent_over_time.go
  pkg/streamingpromql/operators/functions/function_over_range_vector.go
  pkg/streamingpromql/operators/selectors/range_vector_selector.go
  pkg/streamingpromql/operators/subquery.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/range_vector_operator.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/range_vector_operator_test.go
  pkg/streamingpromql/types/operator.go
Labels: changelog-not-needed

#12520 [r355] Fix ruler remotequerier request body consumption on retries
  CHANGELOG.md
  pkg/ruler/remotequerier.go
  pkg/ruler/remotequerier_test.go
Labels: backport

#12519 [r354] Fix ruler remotequerier request body consumption on retries
  CHANGELOG.md
  pkg/ruler/remotequerier.go
  pkg/ruler/remotequerier_test.go
Labels: backport

#12507 streamingpromql: handle adaptive metrics reserved functions in `functionNeedsDeduplication`
  pkg/streamingpromql/operators/functions/functions.pb.go
  pkg/streamingpromql/operators/functions/functions.proto
  pkg/streamingpromql/planning.go
Labels: changelog-not-needed

#12533 [r356] Add CLI flag to set max Alertmanager notification batch size
  CHANGELOG.md
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/ruler/manager.go
  pkg/ruler/ruler.go
Labels: backport

#12537 bring in latest parquet-common with unmerged pr 107
  go.mod
  go.sum
  vendor/github.com/prometheus-community/parquet-common/search/constraint.go
  vendor/github.com/prometheus-community/parquet-common/search/iterators.go
  vendor/modules.txt
Labels: changelog-not-needed

#12534 [r355] Add CLI flag to set max Alertmanager notification batch size
  CHANGELOG.md
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/ruler/manager.go
  pkg/ruler/ruler.go
Labels: backport

#12540 [r357] Correctly decrement numCompactionsInProgress for periodic compactions
  CHANGELOG.md
  pkg/ingester/ingester.go
Labels: backport

#12544 [r355] Correctly decrement numCompactionsInProgress for periodic compactions
  CHANGELOG.md
  pkg/ingester/ingester.go
Labels: backport

#12545 [r354] Correctly decrement numCompactionsInProgress for periodic compactions
  CHANGELOG.md
  pkg/ingester/ingester.go
Labels: backport

#12549 MQE: add trace spans
  pkg/streamingpromql/engine.go
  pkg/streamingpromql/engine_test.go
  pkg/streamingpromql/evaluator.go
  pkg/streamingpromql/planning.go
  pkg/streamingpromql/query.go
Labels: changelog-not-needed

#12182 DOCS: to show livenessProbe is supported by chart
  operations/helm/charts/mimir-distributed/CHANGELOG.md
  operations/helm/charts/mimir-distributed/values.yaml
Labels: release/notified-changelog-cut

#12554 [r355] Patch backwards compatability test for easier backporting
  integration/backward_compatibility_test.go
Labels: changelog-not-needed

#12555 [r354] Patch backwards compatability test for easier backporting
  integration/backward_compatibility_test.go
Labels: changelog-not-needed

#12557 [r352] Patch backwards compatability test for easier backporting
  integration/backward_compatibility_test.go
Labels: changelog-not-needed

#12558 [r351] Patch backwards compatability test for easier backporting
  integration/backward_compatibility_test.go
Labels: changelog-not-needed

#12541 mimirpb: Preserve inconsistent metric metadata in RW1 to 2 conversion
  pkg/mimirpb/prealloc_rw2.go
  pkg/mimirpb/prealloc_rw2_test.go
Labels: changelog-not-needed
