Repository grafana/mimir, pull requests merged in 2025-07, with the labels that each got.

#11872 blockbuilder: add cortex_blockbuilder_tsdb_last_successful_compact_and_upload_timestamp_seconds
  pkg/blockbuilder/metrics.go
  pkg/blockbuilder/tsdb.go
Labels: changelog-not-needed

#11890 fix(ingester): Keep read only when any number of compactions in progress
  CHANGELOG.md
  pkg/ingester/downscale.go
  pkg/ingester/downscale_test.go
  pkg/ingester/ingester.go
  pkg/ingester/metrics.go
Labels: bug

#11938 Fix broken test
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass_test.go
Labels: changelog-not-needed

#11934 Upgrade alerting from dc5663fe02aa to cea2d1683945
  go.mod
  go.sum
  vendor/github.com/grafana/alerting/definition/alertmanager.go
  vendor/modules.txt
Labels: changelog-not-needed

#11942 actions: trigger backend-enterprise updates on weekly releases
  .github/workflows/trigger-backend-enterprise-update.yml
Labels: changelog-not-needed

#11913 Alertmanager: Restore SmtpFrom and StaticHeaders
  integration/alertmanager_test.go
  integration/e2emimir/client.go
  pkg/alertmanager/alertspb/alerts.pb.go
  pkg/alertmanager/alertspb/alerts.proto
  pkg/alertmanager/alertspb/compat.go
  pkg/alertmanager/api_grafana.go
  pkg/alertmanager/api_grafana_test.go
  pkg/alertmanager/config.go
  pkg/alertmanager/config_test.go
Labels: changelog-not-needed

#11683 MQE: Add labels.Label of SeriesMetadata to MQE memory tracker
  pkg/streamingpromql/engine_test.go
  pkg/streamingpromql/operators/aggregations/aggregation.go
  pkg/streamingpromql/operators/aggregations/count_values.go
  pkg/streamingpromql/operators/aggregations/quantile.go
  pkg/streamingpromql/operators/aggregations/topkbottomk/instant_query.go
  pkg/streamingpromql/operators/aggregations/topkbottomk/range_query.go
  pkg/streamingpromql/operators/binops/and_unless_binary_operation.go
  pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation.go
  pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation.go
  pkg/streamingpromql/operators/binops/or_binary_operation.go
  pkg/streamingpromql/operators/deduplicate_and_merge.go
  pkg/streamingpromql/operators/functions/absent.go
  pkg/streamingpromql/operators/functions/absent_over_time.go
  pkg/streamingpromql/operators/functions/common.go
  pkg/streamingpromql/operators/functions/common_test.go
  pkg/streamingpromql/operators/functions/function_over_instant_vector_test.go
  pkg/streamingpromql/operators/functions/histogram_function.go
  pkg/streamingpromql/operators/functions/label.go
  pkg/streamingpromql/operators/scalars/scalar_to_instant_vector.go
  pkg/streamingpromql/operators/selectors/selector.go
  pkg/streamingpromql/operators/test_operator.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/operator.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/operator_test.go
  pkg/streamingpromql/types/data.go
  pkg/streamingpromql/types/limiting_pool.go
  pkg/streamingpromql/types/limiting_pool_test.go
  pkg/util/limiter/memory_consumption.go
Labels: changelog-not-needed

#11796 Alertmanager: Save the original config string when updating Grafana configuration
  pkg/alertmanager/api_grafana.go
  pkg/alertmanager/api_grafana_test.go
Labels: component/alertmanager, changelog-not-needed

#11936 MQE: encode query plan node type as an integer, rather than a string
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/node.go
  pkg/streamingpromql/planning/core/aggregate_expression.go
  pkg/streamingpromql/planning/core/binary_expression.go
  pkg/streamingpromql/planning/core/function_call.go
  pkg/streamingpromql/planning/core/matrix_selector.go
  pkg/streamingpromql/planning/core/number_literal.go
  pkg/streamingpromql/planning/core/string_literal.go
  pkg/streamingpromql/planning/core/subquery.go
  pkg/streamingpromql/planning/core/unary_expression.go
  pkg/streamingpromql/planning/core/vector_selector.go
  pkg/streamingpromql/planning/plan.go
  pkg/streamingpromql/planning/plan.pb.go
  pkg/streamingpromql/planning/plan.proto
  pkg/streamingpromql/planning/plan_test.go
  pkg/streamingpromql/planning_test.go
Labels: changelog-not-needed

#11956 MQE: adjust behaviour of binary operations with `on (__name__)` to match Prometheus
  pkg/streamingpromql/operators/binops/binary_operation.go
  pkg/streamingpromql/testdata/ours/binary_operators.test
Labels: changelog-not-needed

#11963 MQE: Fix estimations in TestMemoryConsumptionLimit_SingleQueries
  pkg/streamingpromql/engine_test.go
Labels: changelog-not-needed

#11985 Alertmanager: Check error code fron pre-notify hooks, and ignore 204.
  pkg/alertmanager/notify_hooks_notifier.go
  pkg/alertmanager/notify_hooks_notifier_test.go
Labels: changelog-not-needed

#11989 MQE: fix issue where a query with a common subexpression could return incorrect results
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/series_data_ring_buffer.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/series_data_ring_buffer_test.go
Labels: backport r345, backport r346, changelog-not-needed, backport r347, backport r348, backport r349, backport r350

#12018 fix(parquet store gateway): obey query sharding matchers
  pkg/storegateway/parquet_bucket_store.go
  pkg/storegateway/parquet_bucket_store_test.go
  pkg/storegateway/parquet_bucket_stores_test.go
Labels: changelog-not-needed

#11955 MQE: encode query plan functions as an integer, rather than a string, and simplify function handling
  pkg/streamingpromql/functions_test.go
  pkg/streamingpromql/operators/functions/factories.go
  pkg/streamingpromql/operators/functions/factories_test.go
  pkg/streamingpromql/operators/functions/functions.go
  pkg/streamingpromql/operators/functions/functions.pb.go
  pkg/streamingpromql/operators/functions/functions.proto
  pkg/streamingpromql/optimize/plan/skip_histogram_decoding.go
  pkg/streamingpromql/planning.go
  pkg/streamingpromql/planning/core/core.pb.go
  pkg/streamingpromql/planning/core/core.proto
  pkg/streamingpromql/planning/core/function_call.go
  pkg/streamingpromql/planning/core/function_call_test.go
  pkg/streamingpromql/planning_test.go
Labels: changelog-not-needed

#11987 blockbuilder: refactor TSDBBuilder.Process
  pkg/blockbuilder/blockbuilder.go
  pkg/blockbuilder/tsdb.go
  pkg/blockbuilder/tsdb_test.go
Labels: changelog-not-needed

#12017 docs: Update release shepherd for 2.17
  RELEASE.md
Labels: changelog-not-needed

#12020 fix(parquet store gateway): panic in Series call with SkipChunks
  pkg/storegateway/parquet_bucket_store.go
  pkg/storegateway/parquet_bucket_store_test.go
Labels: changelog-not-needed

#12021 parquet-converter debug log messages
  pkg/parquetconverter/parquet_converter.go
Labels: changelog-not-needed

#11969 operations: Add knob for controlling ingest-storage producer record version
  operations/mimir-tests/test-ingest-storage-autoscaling-custom-stabilization-window-generated.yaml
  operations/mimir-tests/test-ingest-storage-autoscaling-multiple-triggers-generated.yaml
  operations/mimir-tests/test-ingest-storage-autoscaling-one-trigger-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-10-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-11-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-2-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-3-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-4-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-5a-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-5b-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-6-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-7-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-8-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-9-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-final-generated.yaml
  operations/mimir/ingest-storage.libsonnet
Labels: jsonnet, changelog-not-needed

#12024 Update IngesterHasNotShippedBlocks to be block-builder aware
  docs/sources/mimir/manage/mimir-runbooks/_index.md
  operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
  operations/mimir-mixin-compiled-baremetal/alerts.yaml
  operations/mimir-mixin-compiled-gem/alerts.yaml
  operations/mimir-mixin-compiled/alerts.yaml
  operations/mimir-mixin/alerts/blocks.libsonnet
  operations/mimir-mixin/alerts/ingest-storage.libsonnet
Labels: changelog-not-needed

#12029 Alertmanager: Improve metrics and add tracing for pre-notify hooks.
  pkg/alertmanager/alertmanager_metrics.go
  pkg/alertmanager/alertmanager_metrics_test.go
  pkg/alertmanager/notify_hooks_notifier.go
  pkg/alertmanager/notify_hooks_notifier_test.go
Labels: changelog-not-needed

#12027 mqe: init Subquery childStats in a NewSubquery to avoid panic
  pkg/streamingpromql/operators/subquery.go
  pkg/streamingpromql/operators/subquery_test.go
  pkg/streamingpromql/planning/core/subquery.go
Labels: changelog-not-needed

#12041 Update the changelog for release 2.17.0.rc.0
  CHANGELOG.md
Labels: changelog-not-needed

#12045 chore: Update renovate to keep release-2.17 branch up to date
  renovate.json5
Labels: changelog-not-needed

#12055 Chore: remove unused block stats in compactor's GatherBlockHealthStats()
  pkg/storage/tsdb/block/index.go
  tools/tsdb-index-health/main_test.go
Labels: changelog-not-needed

#12070 Chore: instruct claude to end comments with a period
  docs/internal/contributing/design-patterns-and-conventions.md
Labels: changelog-not-needed

#12071 Update cluster validation integration test with OTLP push request
  integration/ingester_test.go
Labels: changelog-not-needed

#12074 Update dskit to skip tracing configuration when no env is defined
  CHANGELOG.md
  docs/sources/mimir/configure/configure-tracing.md
  go.mod
  go.sum
  pkg/frontend/v1/frontend_test.go
  pkg/querier/engine/query_tracker_test.go
  vendor/github.com/grafana/dskit/tracing/otel.go
  vendor/github.com/grafana/dskit/tracing/otel_jaeger.go
  vendor/modules.txt
Labels: backport release-2.17

#12079 [r351] Alertmanager: Add an endpoint to get the full state #12014 #12078
  integration/alertmanager_test.go
  integration/e2emimir/client.go
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_test.go
  pkg/alertmanager/distributor_test.go
  pkg/api/api.go
Labels: changelog-not-needed

#12053 Improve docs for blocked requests, blocked queries and limited queries config options
  cmd/mimir/config-descriptor.json
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/frontend/querymiddleware/limits.go
  pkg/frontend/querymiddleware/limits_test.go
  pkg/frontend/querymiddleware/query_blocker_test.go
  pkg/frontend/querymiddleware/query_limiter_test.go
  pkg/frontend/querymiddleware/request_blocker_test.go
  pkg/frontend/querymiddleware/roundtrip_test.go
  pkg/mimirtool/config/inspect.go
  pkg/util/validation/blocked_query.go
  pkg/util/validation/blocked_request.go
  pkg/util/validation/limited_query.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
  tools/doc-generator/parse/parser.go
  tools/doc-generator/write/writer.go
  tools/doc-generator/write/writer_test.go
Labels: changelog-not-needed

#12091 parquet store-gateways: open labels file from bucket with flag
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  development/mimir-microservices-mode/docker-compose.jsonnet
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/storage/parquet/block/lazy_reader.go
  pkg/storage/parquet/block/reader.go
  pkg/storage/parquet/block/reader_pool.go
  pkg/storage/tsdb/config.go
  pkg/storegateway/parquet_bucket_store.go
  pkg/storegateway/parquet_bucket_store_test.go
  pkg/storegateway/parquet_bucket_stores.go
Labels: changelog-not-needed

#12099 chore: Update dskit
  go.mod
  go.sum
  vendor/github.com/grafana/dskit/ring/basic_lifecycler.go
  vendor/github.com/grafana/dskit/ring/multi_partition_instance_ring.go
  vendor/github.com/grafana/dskit/ring/partition_instance_lifecycler.go
  vendor/github.com/grafana/dskit/ring/partition_ring.go
  vendor/github.com/grafana/dskit/ring/partition_ring_editor.go
  vendor/modules.txt
Labels: changelog-not-needed

#12100 Refactoring: move X-Scope-OrgID HTTP header injection into EncodeLabelsSeriesQueryRequest() and EncodeMetricsQueryRequest()
  pkg/frontend/querymiddleware/codec.go
  pkg/frontend/querymiddleware/codec_test.go
  pkg/frontend/querymiddleware/labels_query_optimizer.go
  pkg/frontend/querymiddleware/limits.go
Labels: changelog-not-needed

#12101 Refactoring: remove querymiddleware.Codec interface
  pkg/frontend/frontend_test.go
  pkg/frontend/querymiddleware/codec.go
  pkg/frontend/querymiddleware/codec_json_test.go
  pkg/frontend/querymiddleware/codec_protobuf_test.go
  pkg/frontend/querymiddleware/codec_test.go
  pkg/frontend/querymiddleware/error_caching_test.go
  pkg/frontend/querymiddleware/generic_query_cache_test.go
  pkg/frontend/querymiddleware/labels_query_cache_test.go
  pkg/frontend/querymiddleware/labels_query_optimizer_test.go
  pkg/frontend/querymiddleware/limits_test.go
  pkg/frontend/querymiddleware/model_extra_test.go
  pkg/frontend/querymiddleware/query_limiter_test.go
  pkg/frontend/querymiddleware/querysharding_test.go
  pkg/frontend/querymiddleware/request_validation_test.go
  pkg/frontend/querymiddleware/response_parsing_edge_cases_test.go
  pkg/frontend/querymiddleware/results_cache_test.go
  pkg/frontend/querymiddleware/roundtrip_test.go
  pkg/frontend/querymiddleware/split_and_cache_test.go
  pkg/frontend/v2/frontend_scheduler_adapter_test.go
  pkg/frontend/v2/frontend_test.go
  pkg/mimir/modules.go
Labels: changelog-not-needed

#12110 Revert "Update dimitarvdimitrov/shared-workflows digest to 0e7ecbf (main)"
  .github/workflows/flaky-tests.yml
Labels: changelog-not-needed

#12119 [2.17] Update mimir-prometheus
  go.mod
  go.sum
  vendor/github.com/prometheus/prometheus/storage/remote/write.go
  vendor/github.com/prometheus/prometheus/tsdb/wlog/live_reader.go
  vendor/github.com/prometheus/prometheus/tsdb/wlog/watcher.go
  vendor/modules.txt
Labels: changelog-not-needed

#12038 fix(frontend): queries with duration expression
  CHANGELOG.md
  pkg/frontend/querymiddleware/durations.go
  pkg/frontend/querymiddleware/durations_test.go
  pkg/frontend/querymiddleware/querysharding_test.go
  pkg/frontend/querymiddleware/roundtrip.go
  pkg/frontend/querymiddleware/roundtrip_test.go
  pkg/frontend/querymiddleware/split_by_instant_interval_test.go
Labels: release/notified-changelog-cut

#12103 Update grafana/alerting to 8eef376f49f8 & alertmanager to be61a673dee6
  go.mod
  go.sum
  pkg/alertmanager/sender_test.go
  vendor/github.com/grafana/alerting/http/client.go
  vendor/github.com/grafana/alerting/http/oauth2.go
  vendor/github.com/grafana/alerting/http/testing.go
  vendor/github.com/grafana/alerting/notify/factory.go
  vendor/github.com/grafana/alerting/notify/receivers.go
  vendor/github.com/grafana/alerting/notify/testing.go
  vendor/github.com/grafana/alerting/receivers/webhook/config.go
  vendor/github.com/grafana/alerting/receivers/webhook/testing.go
  vendor/github.com/prometheus/alertmanager/config/notifiers.go
  vendor/github.com/prometheus/alertmanager/notify/webhook/webhook.go
  vendor/modules.txt
Labels: changelog-not-needed, dependency-update

#12142 add note about not using monolithic mode for large-scale deployments
  docs/sources/mimir/references/architecture/deployment-modes/index.md
Labels: type/docs, changelog-not-needed

#12143 Docs: Cross-reference native histogram specification
  docs/sources/mimir/send/native-histograms/_index.md
  docs/sources/mimir/visualize/native-histograms/_index.md
Labels: type/docs, changelog-not-needed

#12129 Alertmanager: Grafana configuration status API endpoint
  development/common/config/nginx.conf.template
  integration/alertmanager_test.go
  integration/e2emimir/client.go
  pkg/alertmanager/api_grafana.go
  pkg/alertmanager/api_grafana_test.go
  pkg/api/api.go
Labels: component/alertmanager, changelog-not-needed

#12165 [r351] Block-builder-scheduler: fix bugs in handling of partitions with no commit (#12130)
  CHANGELOG.md
  pkg/blockbuilder/scheduler/metrics.go
  pkg/blockbuilder/scheduler/scheduler.go
  pkg/blockbuilder/scheduler/scheduler_test.go
Labels: backport, changelog-not-needed

#12168 Replace sort.SliceIsSorted with slices.IsSortedFunc
  Makefile
  pkg/ingester/shipper_test.go
  pkg/mimirpb/timeseries_test.go
Labels: chore, changelog-not-needed

#12060 distributor: Expermental support for producing ingest-storage records in format V2
  pkg/mimirpb/prealloc_rw2.go
  pkg/mimirpb/prealloc_rw2_test.go
  pkg/mimirpb/symbols.go
  pkg/mimirpb/symbols_test.go
  pkg/storage/ingest/version.go
  pkg/storage/ingest/version_test.go
Labels: component/distributor, changelog-not-needed

#12183 chore(localdev): bump otel collector and enable native histograms
  development/mimir-monolithic-mode/config/otel-collector-otlp-push-config.yaml
  development/mimir-monolithic-mode/config/otel-collector-remote-write-config.yaml
  development/mimir-monolithic-mode/docker-compose.yml
Labels: changelog-not-needed

#11848 Parameterize metric/label name validation scheme
  CHANGELOG.md
  Makefile
  go.mod
  go.sum
  integration/kv_test.go
  pkg/distributor/distributor.go
  pkg/distributor/validate.go
  pkg/distributor/validate_test.go
  pkg/frontend/querymiddleware/request_validation.go
  pkg/frontend/querymiddleware/request_validation_test.go
  pkg/mimir/promexts.go
  pkg/mimirtool/commands/analyse_rulefiles.go
  pkg/mimirtool/commands/analyse_rulefiles_test.go
  pkg/mimirtool/commands/analyse_rules_test.go
  pkg/mimirtool/commands/rules.go
  pkg/mimirtool/rules/parser.go
  pkg/mimirtool/rules/parser_test.go
  pkg/mimirtool/rules/rules.go
  pkg/querier/cardinality_analysis_handler_test.go
  pkg/querier/stats_renderer_test.go
  pkg/ruler/api.go
  pkg/ruler/compat.go
  pkg/ruler/manager.go
  pkg/ruler/ruler.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
  vendor/github.com/prometheus/alertmanager/matchers/compat/parse.go
  vendor/github.com/prometheus/prometheus/model/labels/validate.go
  vendor/github.com/prometheus/prometheus/model/relabel/relabel.go
  vendor/github.com/prometheus/prometheus/model/rulefmt/rulefmt.go
  vendor/github.com/prometheus/prometheus/notifier/manager.go
  vendor/github.com/prometheus/prometheus/rules/manager.go
  vendor/github.com/prometheus/prometheus/scrape/scrape.go
  vendor/modules.txt
Labels: enhancement, component/querier, component/query-frontend

#12190 operations: Allow ingest-storage record version to be increased to v2
  operations/mimir/ingest-storage.libsonnet
Labels: jsonnet, changelog-not-needed

#12187 jsonnet: Make query-scheduler a required component
  CHANGELOG.md
  operations/mimir-tests/test-without-query-scheduler-generated.yaml
  operations/mimir-tests/test-without-query-scheduler.jsonnet
  operations/mimir/autoscaling.libsonnet
  operations/mimir/config.libsonnet
  operations/mimir/querier.libsonnet
  operations/mimir/query-frontend.libsonnet
  operations/mimir/query-scheduler.libsonnet
Labels: jsonnet, release/notified-changelog-cut

#12048 store-gateway: Fix goroutine leak in LabelValues when using errgroup …
  CHANGELOG.md
  pkg/storegateway/bucket.go
Labels: release/notified-changelog-cut

#12232 build: Fix git worktree warnings in Docker containers
  Makefile
  tools/git-worktree-volumes.sh
Labels: changelog-not-needed

#12197 index planning: implement cost model predicate
  pkg/ingester/lookupplan/csv_test_data_test.go
  pkg/ingester/lookupplan/interfaces.go
  pkg/ingester/lookupplan/predicate.go
  pkg/ingester/lookupplan/predicate_test.go
  pkg/ingester/lookupplan/testdata/cardinality_estimation_test_cases.csv
  pkg/ingester/lookupplan/testdata/filter_cost_test_cases.csv
  pkg/ingester/lookupplan/testdata/index_lookup_cost_test_cases.csv
Labels: changelog-not-needed

#12242 chore: Autofix to make #nosec suppressions also legible to semgrep
  pkg/alertmanager/multitenant.go
Labels: changelog-not-needed

#12166 ingest-storage: Split very large RW2.0 requests into multiple Kafka records
  pkg/mimirpb/custom.go
  pkg/mimirpb/custom_test.go
  pkg/mimirpb/prealloc_rw2.go
  pkg/mimirpb/prealloc_rw2_test.go
  pkg/mimirpb/split.go
  pkg/mimirpb/split_test.go
  pkg/mimirpb/symbols.go
  pkg/mimirpb/symbols_test.go
  pkg/mimirpb/timeseries.go
  pkg/storage/ingest/version.go
  pkg/storage/ingest/writer.go
  pkg/storage/ingest/writer_test.go
Labels: component/distributor, sigyn, changelog-not-needed

#12215 Distributor: Add flag for name validation scheme
  CHANGELOG.md
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  docs/sources/mimir/configure/configuration-parameters/index.md
  go.mod
  integration/distributor_test.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
  pkg/util/validation/validation_scheme_value.go
  pkg/util/validation/validation_scheme_value_test.go
Labels: release/notified-changelog-cut

#12219 pkg/util/validation: Rename ValidationScheme override to NameValidationScheme
  pkg/distributor/validate.go
  pkg/distributor/validate_test.go
  pkg/ruler/compat.go
  pkg/ruler/manager.go
  pkg/ruler/ruler.go
  pkg/util/validation/limits.go
Labels: chore, changelog-not-needed

#12258 Alertmanager: Add test for strict initialization
  pkg/alertmanager/multitenant_test.go
Labels: changelog-not-needed

#12262 [r352] Revert otlp: Stick to OTLP vocabulary on invalid label value length error
  CHANGELOG.md
  pkg/distributor/errors.go
  pkg/distributor/otel.go
  pkg/distributor/otel_test.go
  pkg/distributor/validate.go
  pkg/distributor/validate_test.go
Labels: changelog-not-needed

#12265 [r353] Revert "otlp: Stick to OTLP vocabulary on invalid label value length error (#11889)"
  CHANGELOG.md
  pkg/distributor/errors.go
  pkg/distributor/otel.go
  pkg/distributor/otel_test.go
  pkg/distributor/validate.go
  pkg/distributor/validate_test.go
Labels: changelog-not-needed

#12251 MQE: change log message to disambiguate from query-frontend query stats log messages
  pkg/streamingpromql/engine_test.go
  pkg/streamingpromql/query.go
Labels: changelog-not-needed

#12252 Refactor query response Protobuf definition
  pkg/api/protobuf_codec_test.go
  pkg/distributor/distributor_test.go
  pkg/distributor/errors.go
  pkg/distributor/errors_test.go
  pkg/distributor/otel_test.go
  pkg/distributor/push_test.go
  pkg/frontend/querymiddleware/codec_protobuf.go
  pkg/frontend/querymiddleware/codec_protobuf_test.go
  pkg/frontend/querymiddleware/split_and_cache_test.go
  pkg/ingester/circuitbreaker_test.go
  pkg/ingester/errors.go
  pkg/ingester/errors_test.go
  pkg/ingester/instance_limits_test.go
  pkg/mimirpb/errors.go
  pkg/mimirpb/errors_test.go
  pkg/mimirpb/mimir.pb.go
  pkg/mimirpb/mimir.proto
  pkg/mimirpb/query_response_extra.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/error_translate_queryable.go
  pkg/ruler/compat_test.go
  pkg/ruler/remotequerier_decoder.go
  pkg/ruler/remotequerier_test.go
  pkg/storage/ingest/pusher_test.go
  pkg/storegateway/bucket.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_test.go
  pkg/util/globalerror/grpc_test.go
Labels: changelog-not-needed
