Repository grafana/mimir, pull requests merged in 2025-09, with the labels that each got.

#12552 Introduce `FromSamplesToFPoints` and `FromHistogramsToHPoints`
  pkg/mimirpb/compat.go
  pkg/mimirpb/compat_test.go
Labels: changelog-not-needed

#12480 docs: Update shuffle sharding for ingest storage
  docs/sources/mimir/configure/configure-shuffle-sharding/index.md
Labels: changelog-not-needed

#12535 [r354] Add CLI flag to set max Alertmanager notification batch size
  CHANGELOG.md
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/ruler/manager.go
  pkg/ruler/ruler.go
Labels: backport

#12515 Docs: overview of ingest storage architecture (pt. 2)
  docs/sources/mimir/get-started/about-grafana-mimir-architecture/about-ingest-storage-architecture/index.md
Labels: changelog-not-needed

#12596 refactor: change how loggers are passed to MQE
  pkg/frontend/querymiddleware/querysharding_test_utils_test.go
  pkg/mimir/modules.go
  pkg/querier/dispatcher_test.go
  pkg/querier/engine/config.go
  pkg/querier/querier.go
  pkg/streamingpromql/benchmarks/comparison_test.go
  pkg/streamingpromql/config.go
  pkg/streamingpromql/engine.go
  pkg/streamingpromql/engine_concurrency_test.go
  pkg/streamingpromql/engine_fuzz_test.go
  pkg/streamingpromql/engine_test.go
  pkg/streamingpromql/functions_test.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass_test.go
  pkg/streamingpromql/optimize/plan/skip_histogram_decoding_test.go
  pkg/streamingpromql/planning.go
  tools/check-for-disabled-but-supported-mqe-test-cases/main.go
Labels: changelog-not-needed

#12593 Replace BlockBuilderLagging alert with BlockBuilderSchedulerPendingJobs
  docs/sources/mimir/manage/mimir-runbooks/_index.md
  operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
  operations/mimir-mixin-compiled-baremetal/alerts.yaml
  operations/mimir-mixin-compiled-gem/alerts.yaml
  operations/mimir-mixin-compiled/alerts.yaml
  operations/mimir-mixin/alerts/ingest-storage.libsonnet
Labels: changelog-not-needed

#12610 Update about-versioning for removed deprecated HA tracker timeout configs
  docs/sources/mimir/configure/about-versioning.md
Labels: changelog-not-needed

#12614 Update 2.17.1 changelog
  CHANGELOG.md
Labels: changelog-not-needed

#12612 Update about-versioning for experimental query frontend rewriting middleware
  docs/sources/mimir/configure/about-versioning.md
Labels: changelog-not-needed

#12609 docs: query-scheduler is now a required component
  docs/sources/mimir/get-started/about-grafana-mimir-architecture/index.md
  docs/sources/mimir/get-started/about-grafana-mimir-architecture/read-path.svg
  docs/sources/mimir/references/architecture/components/alertmanager.md
  docs/sources/mimir/references/architecture/components/query-frontend/index.md
  docs/sources/mimir/references/architecture/components/query-frontend/query-frontend-architecture.png
  docs/sources/mimir/references/architecture/components/query-scheduler/index.md
  docs/sources/mimir/references/architecture/components/ruler/ruler-remote.svg
  docs/sources/mimir/references/architecture/components/store-gateway.md
  docs/sources/mimir/references/architecture/deployment-modes/microservices-mode.svg
Labels: changelog-not-needed

#12620 chore: replace ingester start/stop boilerplate in tests
  pkg/ingester/circuitbreaker_test.go
  pkg/ingester/downscale_test.go
  pkg/ingester/ingester_early_compaction_test.go
  pkg/ingester/ingester_test.go
  pkg/ingester/lifecycle_test.go
  pkg/ingester/owned_series_test.go
  pkg/ingester/tenants_http_test.go
Labels: changelog-not-needed

#12621 Apply review suggestion to about-versioning
  docs/sources/mimir/configure/about-versioning.md
Labels: changelog-not-needed

#12500 continuous-test: Add new test for verifying ingest-storage record correctness
  cmd/mimir-continuous-test/main.go
  cmd/mimir/help-all.txt.tmpl
  cmd/mimir/help.txt.tmpl
  pkg/continuoustest/config.go
  pkg/continuoustest/ingest_storage_record.go
  pkg/continuoustest/ingest_storage_record_test.go
  pkg/mimir/modules.go
  pkg/storage/ingest/version.go
Labels: component/continuous-test, changelog-not-needed

#12617 ruler: Refactor GroupLoader to use the same filesystem abstraction as the mapper
  pkg/mimir/modules.go
  pkg/ruler/compat.go
  pkg/ruler/compat_test.go
  pkg/ruler/manager.go
  pkg/ruler/manager_test.go
  pkg/ruler/mapper.go
  pkg/ruler/ruler_test.go
Labels: component/ruler, changelog-not-needed

#12624 docs: update run-production-environment-with-helm with details about ingest storage
  docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
Labels: changelog-not-needed

#12668 CI: Notify MQE maintainers when pkg/streamingpromql tests fail on vendor PRs
  .github/workflows/scripts/run-unit-tests-group.sh
  .github/workflows/test-build-deploy.yml
Labels: changelog-not-needed

#12686 MQE: improve docs for "Binary operations that produce no series"
  docs/sources/mimir/references/architecture/mimir-query-engine.md
Labels: changelog-not-needed

#12646 MQE: report query stats for remotely executed queries
  integration/query_frontend_samples_processed_test.go
  integration/query_frontend_test.go
  pkg/frontend/querymiddleware/limits.go
  pkg/frontend/querymiddleware/limits_test.go
  pkg/frontend/v2/remoteexec.go
  pkg/frontend/v2/remoteexec_test.go
  pkg/querier/dispatcher.go
  pkg/querier/dispatcher_test.go
  pkg/querier/querierpb/querier.pb.go
  pkg/querier/querierpb/querier.proto
  pkg/querier/worker/scheduler_processor.go
  pkg/querier/worker/scheduler_processor_test.go
  pkg/streamingpromql/evaluator.go
  pkg/streamingpromql/optimize/plan/remoteexec/executor.go
  pkg/streamingpromql/optimize/plan/remoteexec/instant_vector_operator.go
  pkg/streamingpromql/optimize/plan/remoteexec/operators.go
  pkg/streamingpromql/optimize/plan/remoteexec/operators_test.go
  pkg/streamingpromql/optimize/plan/remoteexec/range_vector_operator.go
  pkg/streamingpromql/optimize/plan/remoteexec/scalar_operator.go
Labels: changelog-not-needed

#12721 Use util_log to initialize logger in tsdb-* tools
  tools/tsdb-gaps/main.go
  tools/tsdb-print-chunk/main.go
  tools/tsdb-series/main.go
Labels: changelog-not-needed

#12720 Upgrade Failsafe-go to 0.8.2
  go.mod
  go.sum
  pkg/ingester/circuitbreaker.go
  vendor/github.com/bits-and-blooms/bitset/README.md
  vendor/github.com/bits-and-blooms/bitset/bitset.go
  vendor/github.com/bits-and-blooms/bitset/leading_zeros_18.go
  vendor/github.com/bits-and-blooms/bitset/leading_zeros_19.go
  vendor/github.com/bits-and-blooms/bitset/pext.gen.go
  vendor/github.com/bits-and-blooms/bitset/popcnt.go
  vendor/github.com/bits-and-blooms/bitset/popcnt_19.go
  vendor/github.com/bits-and-blooms/bitset/popcnt_amd64.go
  vendor/github.com/bits-and-blooms/bitset/popcnt_amd64.s
  vendor/github.com/bits-and-blooms/bitset/popcnt_generic.go
  vendor/github.com/bits-and-blooms/bitset/select.go
  vendor/github.com/bits-and-blooms/bitset/trailing_zeros_18.go
  vendor/github.com/bits-and-blooms/bitset/trailing_zeros_19.go
  vendor/github.com/failsafe-go/failsafe-go/CHANGELOG.md
  vendor/github.com/failsafe-go/failsafe-go/README.md
  vendor/github.com/failsafe-go/failsafe-go/circuitbreaker/circuitbreaker.go
  vendor/github.com/failsafe-go/failsafe-go/circuitbreaker/circuitbreakerbuilder.go
  vendor/github.com/failsafe-go/failsafe-go/circuitbreaker/circuitbreakerexecutor.go
  vendor/github.com/failsafe-go/failsafe-go/circuitbreaker/circuitstates.go
  vendor/github.com/failsafe-go/failsafe-go/circuitbreaker/circuitstats.go
  vendor/github.com/failsafe-go/failsafe-go/execution.go
  vendor/github.com/failsafe-go/failsafe-go/executor.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/assert.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/ewma.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/median.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/semaphore.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/stats.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/util.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/windows.go
  vendor/github.com/failsafe-go/failsafe-go/policy/policy.go
  vendor/modules.txt
Labels: changelog-not-needed

#12732 Deps: Upgrade Failsafe-go to 0.8.2
  go.mod
  go.sum
  pkg/ingester/circuitbreaker.go
  vendor/github.com/bits-and-blooms/bitset/README.md
  vendor/github.com/bits-and-blooms/bitset/bitset.go
  vendor/github.com/bits-and-blooms/bitset/leading_zeros_18.go
  vendor/github.com/bits-and-blooms/bitset/leading_zeros_19.go
  vendor/github.com/bits-and-blooms/bitset/pext.gen.go
  vendor/github.com/bits-and-blooms/bitset/popcnt.go
  vendor/github.com/bits-and-blooms/bitset/popcnt_19.go
  vendor/github.com/bits-and-blooms/bitset/popcnt_amd64.go
  vendor/github.com/bits-and-blooms/bitset/popcnt_amd64.s
  vendor/github.com/bits-and-blooms/bitset/popcnt_generic.go
  vendor/github.com/bits-and-blooms/bitset/select.go
  vendor/github.com/bits-and-blooms/bitset/trailing_zeros_18.go
  vendor/github.com/bits-and-blooms/bitset/trailing_zeros_19.go
  vendor/github.com/failsafe-go/failsafe-go/CHANGELOG.md
  vendor/github.com/failsafe-go/failsafe-go/README.md
  vendor/github.com/failsafe-go/failsafe-go/circuitbreaker/circuitbreaker.go
  vendor/github.com/failsafe-go/failsafe-go/circuitbreaker/circuitbreakerbuilder.go
  vendor/github.com/failsafe-go/failsafe-go/circuitbreaker/circuitbreakerexecutor.go
  vendor/github.com/failsafe-go/failsafe-go/circuitbreaker/circuitstates.go
  vendor/github.com/failsafe-go/failsafe-go/circuitbreaker/circuitstats.go
  vendor/github.com/failsafe-go/failsafe-go/execution.go
  vendor/github.com/failsafe-go/failsafe-go/executor.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/assert.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/ewma.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/median.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/semaphore.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/stats.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/util.go
  vendor/github.com/failsafe-go/failsafe-go/internal/util/windows.go
  vendor/github.com/failsafe-go/failsafe-go/policy/policy.go
  vendor/modules.txt
Labels: changelog-not-needed

#12740 chore: update shebang to use env for bash in compose scripts
  development/mimir-monolithic-mode/compose-down.sh
  development/mimir-monolithic-mode/compose-up.sh
Labels: changelog-not-needed

#12734 Include more error information in query traces
  pkg/frontend/querymiddleware/limits.go
  pkg/streamingpromql/engine_test.go
  pkg/streamingpromql/query.go
Labels: changelog-not-needed

#12627 distributor: Add truncate and drop options for long label values
  CHANGELOG.md
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  docs/sources/mimir/configure/about-versioning.md
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/distributor/distributor_test.go
  pkg/distributor/validate.go
  pkg/distributor/validate_test.go
  pkg/mimirpb/timeseries.go
  pkg/util/validation/label_value_length_over_limit_strategy.go
  pkg/util/validation/label_value_length_over_limit_strategy_test.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
Labels: enhancement, component/distributor

#12756 Temporarily disable remote execution integration test
  integration/query_frontend_test.go
Labels: changelog-not-needed

#12750 Do not wrap vector-scalar comparison in DeduplicateAndMerge
  pkg/streamingpromql/planning.go
  pkg/streamingpromql/planning_test.go
Labels: changelog-not-needed

#12760 Re-enable disabled integration tests
  integration/query_frontend_test.go
Labels: changelog-not-needed

#12694 perf(rw2): use mimirpb.TimeseriesFromPool()
  pkg/distributor/otel_test.go
  pkg/distributor/otlpappender/mimir_appender.go
  pkg/distributor/otlpappender/mimir_appender_test.go
  pkg/mimirpb/testutil/timeseries.go
Labels: changelog-not-needed

#12762 Fix ingest storage local dev env
  development/mimir-ingest-storage/.data-ingester-zone-a-1/.gitignore
  development/mimir-ingest-storage/.data-ingester-zone-b-1/.gitignore
  development/mimir-ingest-storage/.data-mimir-write-zone-a-2/.gitignore
  development/mimir-ingest-storage/.data-mimir-write-zone-a-3/.gitignore
  development/mimir-ingest-storage/.data-mimir-write-zone-b-1/.gitignore
  development/mimir-ingest-storage/.data-mimir-write-zone-b-2/.gitignore
  development/mimir-ingest-storage/.data-mimir-write-zone-b-3/.gitignore
  development/mimir-ingest-storage/compose-up.sh
  development/mimir-ingest-storage/config/grafana-agent.flow
  development/mimir-ingest-storage/config/mimir.yaml
  development/mimir-ingest-storage/config/runtime.yaml
  development/mimir-ingest-storage/config/tempo.yaml
  development/mimir-ingest-storage/docker-compose.jsonnet
  development/mimir-ingest-storage/docker-compose.yml
Labels: changelog-not-needed

#12737 kafkatool: print write requests as JSON
  tools/kafkatool/dump.go
Labels: changelog-not-needed

#12681 Ingester: Introduce metric cortex_ingester_owned_target_info_series
  CHANGELOG.md
  pkg/ingester/ingester.go
  pkg/ingester/metrics.go
  pkg/ingester/owned_series_test.go
  pkg/ingester/user_tsdb.go
  pkg/ingester/user_tsdb_test.go
Labels: enhancement, component/ingester, area/opentelemetry

#12754 continuous-test: Improve record test logging/metrics, adjust tuneables
  cmd/mimir/help-all.txt.tmpl
  cmd/mimir/help.txt.tmpl
  pkg/continuoustest/ingest_storage_record.go
Labels: changelog-not-needed

#12755 index planning: fix config defaults and validation
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/storage/tsdb/config.go
Labels: changelog-not-needed

#12763 test-build-deploy: Install GitHub CLI in test workflow step
  .github/workflows/scripts/install-gh.sh
  .github/workflows/test-build-deploy.yml
Labels: changelog-not-needed

#12435 Add Compactor Scheduler Skeleton
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  docs/sources/mimir/configure/about-versioning.md
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/compactor/executor.go
  pkg/compactor/executor_test.go
  pkg/compactor/scheduler/rotator.go
  pkg/compactor/scheduler/scheduler.go
  pkg/compactor/scheduler/schedulerpb/scheduler.pb.go
  pkg/compactor/scheduler/schedulerpb/scheduler.proto
  vendor/github.com/failsafe-go/failsafe-go/retrypolicy/doc.go
  vendor/github.com/failsafe-go/failsafe-go/retrypolicy/retry.go
  vendor/github.com/failsafe-go/failsafe-go/retrypolicy/retryexecutor.go
  vendor/modules.txt
Labels: changelog-not-needed

#12791 Provide postings cache factories in ingesters
  pkg/ingester/ingester.go
Labels: changelog-not-needed

#12811 Cleanup: replace `mustLabelMatcher` with `labels.MustNewMatcher`
  pkg/frontend/querymiddleware/astmapper/astmapper_test.go
  pkg/frontend/querymiddleware/astmapper/parallel_test.go
Labels: changelog-not-needed

#12793 Remove usage of ReceiverType in alertmanager
  go.mod
  go.sum
  pkg/alertmanager/alertmanager.go
  vendor/github.com/grafana/alerting/definition/alertmanager.go
  vendor/modules.txt
Labels: changelog-not-needed

#12817 Add Jesús Vázquez as maintainer
  GOVERNANCE.md
  MAINTAINERS.md
Labels: changelog-not-needed

#12821 costattribution.ActiveSeriesTracker: remove duplicate code
  pkg/costattribution/active_tracker.go
Labels: changelog-not-needed

#12820 Fix flaky Test_MaxSeriesAndChunksPerQueryLimitHit
  integration/store_gateway_limits_hit_test.go
Labels: changelog-not-needed

#12827 docs: fix 404 link for metamonitoring
  docs/sources/mimir/manage/monitor-grafana-mimir/deploying-monitoring-mixin.md
Labels: changelog-not-needed

#12807 index planning: Add query cardinality metrics
  pkg/ingester/ingester.go
  pkg/ingester/lookupplan/metrics.go
  pkg/ingester/lookupplan/planner.go
  pkg/ingester/lookupplan/query_stats.go
  pkg/ingester/lookupplan/query_stats_test.go
  pkg/ingester/metrics.go
  pkg/ingester/stats.go
Labels: changelog-not-needed

#12812 Use MQE and upstream test cases to further exercise `cloneExpr`
  pkg/frontend/querymiddleware/astmapper/astmapper.go
  pkg/frontend/querymiddleware/astmapper/astmapper_test.go
Labels: changelog-not-needed

#12851 [r360] storegateway: BucketChunkReader to validate chunk data length
  CHANGELOG.md
  pkg/storegateway/bucket_chunk_reader.go
  pkg/storegateway/bucket_chunk_reader_test.go
Labels: backport, changelog-not-needed

#12854 parquet converter: add `parquet-converter.min-block-duration` flag
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/parquetconverter/parquet_converter.go
Labels: changelog-not-needed

#12511 [Docs] Specify configs only supported in one architecture
  docs/sources/mimir/configure/.gitignore
  docs/sources/mimir/configure/about-ingester-circuit-breakers.md
  docs/sources/mimir/configure/about-reactive-limiters.md
  docs/sources/mimir/configure/configure-spread-minimizing-tokens/index.md
  docs/sources/mimir/configure/configure-zone-aware-replication.md
Labels: type/docs, changelog-not-needed
