Repository grafana/mimir, pull requests merged in 2025-06, with the labels that each got.

#11590 Renovate: Don't update charleskorn/objstore
  renovate.json5
Labels: chore

#11594 Renovate: Re-enable google.golang.org/grpc
  renovate.json5
Labels: chore

#11614 Renovate: Use `config:recommended` preset
  renovate.json5
Labels: chore, type/ci

#11602 operations/mimir: Upstream Jsonnet changes from r334
  CHANGELOG.md
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  docs/sources/mimir/configure/configuration-parameters/index.md
  go.mod
  go.sum
  operations/mimir-tests/test-ingest-storage-autoscaling-custom-stabilization-window-generated.yaml
  operations/mimir-tests/test-ingest-storage-autoscaling-multiple-triggers-generated.yaml
  operations/mimir-tests/test-ingest-storage-autoscaling-one-trigger-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-10-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-11-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-7-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-8-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-9-generated.yaml
  operations/mimir-tests/test-ingest-storage-migration-step-final-generated.yaml
  operations/mimir/ruler.libsonnet
  vendor/github.com/grafana/dskit/cache/memcached_client.go
  vendor/modules.txt
Labels: chore, jsonnet

#11636 Update module github.com/ebitengine/purego to 0.8.3
  go.mod
  go.sum
  vendor/github.com/ebitengine/purego/dlfcn.go
  vendor/github.com/ebitengine/purego/dlfcn_darwin.go
  vendor/github.com/ebitengine/purego/internal/fakecgo/go_libinit.go
  vendor/github.com/ebitengine/purego/internal/fakecgo/libcgo.go
  vendor/github.com/ebitengine/purego/internal/fakecgo/symbols.go
  vendor/modules.txt
Labels: backport release-2.16, backport release-2.15

#11627 Reinstate mimir-otlptranslator fork dependency
  go.mod
  go.sum
  vendor/modules.txt
Labels: chore

#11715 Distributor.prePushValidationMiddleware: Use safe strings for span event attributes
  CHANGELOG.md
  pkg/distributor/distributor.go
Labels: bug, component/distributor

#11724 parquet store-gateways introduce stores interface
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_blocks_http.go
  pkg/storegateway/gateway_test.go
  pkg/storegateway/parquet_bucket_stores.go
  pkg/storegateway/stores.go
Labels: changelog-not-needed

#11726 Don't end trace span early in `Ingester.QueryStream`
  pkg/ingester/ingester.go
Labels: changelog-not-needed

#11720 Alertmanager: stop using isGrafanaTenant
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: component/alertmanager, changelog-not-needed

#11725 Alertmanager: Enforce Grafana template number limit
  pkg/alertmanager/api_grafana.go
Labels: changelog-not-needed

#11743 Configure Renovate to update Go version in all locations in one PR
  renovate.json5
Labels: changelog-not-needed

#11736 golangci-lint: display unlimited same issues
  .golangci.yml
Labels: changelog-not-needed

#11753 Skip changelog check for automated PRs
  .github/workflows/changelog-check.yml
  .github/workflows/helm-weekly-release-pr.yaml
  .github/workflows/update-vendored-mimir-prometheus.yml
  renovate.json5
Labels: changelog-not-needed

#11746 MQE: track memory consumption of `[]promql.Bucket` and `[]promql.Buckets` separately
  pkg/streamingpromql/operators/functions/histogram_function.go
  pkg/util/limiter/memory_consumption.go
Labels: changelog-not-needed

#11518 Update mimir-prometheus on branch pushes
  .github/workflows/update-vendored-mimir-prometheus.yml
Labels: changelog-not-needed

#11765 actions: fix PR title of mimir-prometheus update PRs
  .github/workflows/update-vendored-mimir-prometheus.yml
Labels: changelog-not-needed

#11761 Use app credentials when pushing updated build image from GitHub Actions workflow
  .github/workflows/push-mimir-build-image.yml
Labels: changelog-not-needed

#11760 Really configure Renovate to update Go version in all locations in one PR
  renovate.json5
Labels: changelog-not-needed

#11779 Make output of -modules stable
  cmd/mimir/main.go
Labels: changelog-not-needed

#11767 Update mimir-prometheus @ 226f974e041bed1c679ebd12145f61216af581c6
  go.mod
  go.sum
  pkg/frontend/querymiddleware/querysharding_test.go
  pkg/streamingpromql/testdata/upstream/functions.test
  vendor/github.com/prometheus/prometheus/model/textparse/nhcbparse.go
  vendor/github.com/prometheus/prometheus/promql/functions.go
  vendor/github.com/prometheus/prometheus/promql/parser/functions.go
  vendor/github.com/prometheus/prometheus/promql/promqltest/testdata/functions.test
  vendor/modules.txt
Labels: changelog-not-needed

#11789 [r347] Block-builder-scheduler: Bug: assigned job skipped if start < commit < end (#11785)
  CHANGELOG.md
  pkg/blockbuilder/scheduler/scheduler.go
  pkg/blockbuilder/scheduler/scheduler_test.go
Labels: backport, changelog-not-needed

#11792 Regenerate OTLP files when updating vendored mimir-prometheus
  .github/workflows/update-vendored-mimir-prometheus.yml
Labels: changelog-not-needed

#11731 writes dashboard: add Influx write requests row
  CHANGELOG.md
  docs/sources/mimir/manage/mimir-runbooks/_index.md
  operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
  operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview.json
  operations/mimir-mixin-compiled-baremetal/dashboards/mimir-rollout-progress.json
  operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
  operations/mimir-mixin-compiled-gem/dashboards/mimir-overview.json
  operations/mimir-mixin-compiled-gem/dashboards/mimir-rollout-progress.json
  operations/mimir-mixin-compiled-gem/dashboards/mimir-writes.json
  operations/mimir-mixin-compiled/dashboards/mimir-overview.json
  operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json
  operations/mimir-mixin-compiled/dashboards/mimir-writes.json
  operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
  operations/mimir-mixin/dashboards/writes.libsonnet
Labels: monitoring/dashboards

#11810 OTLP: Fix conversion of non-monotonic sum metrics
  go.mod
  go.sum
  pkg/distributor/otel_test.go
  pkg/distributor/otlp/helper_generated.go
  pkg/distributor/otlp/metrics_to_prw_generated.go
  vendor/github.com/prometheus/prometheus/config/config.go
  vendor/github.com/prometheus/prometheus/promql/parser/parse.go
  vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/helper.go
  vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
  vendor/github.com/prometheus/prometheus/storage/remote/write_handler.go
  vendor/modules.txt
Labels: bug, component/distributor, area/opentelemetry, backport r346, changelog-not-needed, backport r347, backport r348

#11817 [r346] Backport 11810 to r346
  go.mod
  go.sum
  pkg/distributor/otel_test.go
  pkg/distributor/otlp/metrics_to_prw_generated.go
  vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
  vendor/modules.txt
Labels: backport, changelog-not-needed

#11755 Alertmanager: Allow for custom SMTP configs in Grafana email integrations
  integration/alertmanager_test.go
  integration/e2emimir/client.go
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_test.go
  pkg/alertmanager/alertspb/alerts.pb.go
  pkg/alertmanager/alertspb/alerts.proto
  pkg/alertmanager/alertspb/compat.go
  pkg/alertmanager/api_grafana.go
  pkg/alertmanager/api_grafana_test.go
  pkg/alertmanager/config.go
  pkg/alertmanager/config_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: changelog-not-needed

#11875 fix(parquet store gateway): pass blockReader to bucket block constructor
  pkg/storegateway/parquet_bucket_store.go
Labels: changelog-not-needed

#11878 MQE: remove outdated comments in `mergeOneSideHistograms`
  pkg/streamingpromql/operators/series_merging.go
Labels: changelog-not-needed

#11895 Bring BufferHolder back to PrometheusResponse
  pkg/frontend/querymiddleware/model.pb.go
Labels: changelog-not-needed

#11879 MQE: add tests for common subexpression elimination for expressions with multiple children, and add metric on number of selectors eliminated
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass_test.go
Labels: changelog-not-needed

#11841 generate-otlp: run in build image
  .github/workflows/update-vendored-mimir-prometheus.yml
  Makefile
Labels: changelog-not-needed

#6733 [helm-chart] add values for setting annotations and labels for rollout-operator
  operations/helm/charts/mimir-distributed/CHANGELOG.md
  operations/helm/charts/mimir-distributed/templates/_helpers.tpl
  operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
  operations/helm/charts/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/charts/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/charts/mimir-distributed/templates/validate.yaml
  operations/helm/charts/mimir-distributed/values.yaml
  operations/helm/tests/enterprise-https-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/enterprise-https-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/keda-autoscaling-global-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/keda-autoscaling-global-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/keda-autoscaling-metamonitoring-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/keda-autoscaling-metamonitoring-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/large-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/large-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/openshift-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/openshift-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/small-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/small-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-enterprise-component-image-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-enterprise-component-image-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-enterprise-k8s-1.25-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-enterprise-k8s-1.25-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-extra-args-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-extra-args-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-extra-objects-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-extra-objects-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-ingress-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-ingress-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-oss-component-image-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-oss-component-image-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
  operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
  operations/helm/tests/test-oss-topology-spread-constraints-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-oss-topology-spread-constraints-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-requests-and-limits-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-requests-and-limits-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-ruler-dedicated-query-path-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-ruler-dedicated-query-path-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
  operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
  operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
Labels: helm, release/notified-changelog-cut

#11898 docs: Add influx section to HTTP api reference
  docs/sources/mimir/references/http-api/_index.md
Labels: type/docs, changelog-not-needed

#11903 CI: don't re-run unit tests that have already passed when retrying
  .github/workflows/scripts/run-unit-tests-group.sh
Labels: changelog-not-needed

#11900 MQE: simplify logic for "selectors eliminated" metric in CSE, and add "selectors inspected" metric
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass.go
  pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass_test.go
Labels: changelog-not-needed
