Repository grafana/mimir, pull requests merged in 2025-01, with the labels that each got.

#10044 [helm] Si bytes calculation always floor fix
  operations/helm/charts/mimir-distributed/CHANGELOG.md
  operations/helm/charts/mimir-distributed/templates/_helpers.tpl
  operations/helm/tests/small-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
Labels: release/notified-changelog-cut

#10329 tools/copyblocks: Disable pprof endpoint, to satisfy gosec's G108 rule
  .golangci.yml
  CHANGELOG.md
  tools/copyblocks/main.go
Labels: security

#10330 Security: Enable gosec's G114 rule
  .golangci.yml
  pkg/mimirtool/commands/alerts.go
  pkg/mimirtool/commands/loadgen.go
  tools/copyblocks/main.go
  tools/trafficdump/main.go
Labels: security

#10331 Security: Enable gosec linter for G109 rule
  .golangci.yml
  pkg/ruler/api.go
Labels: security

#9770 Close gzip readers after use
  pkg/continuoustest/client_test.go
  pkg/distributor/otel.go
  pkg/storegateway/indexheader/stream_binary_reader.go
  pkg/util/http.go
Labels: chore

#10333 Security: Enable gosec G112 rule
  .golangci.yml
  pkg/frontend/frontend_test.go
  pkg/frontend/v1/frontend_test.go
  pkg/util/gziphandler/gzip_test.go
  pkg/util/instrumentation/metrics.go
Labels: security

#10332 Security: Enable gosec G104 rule
  .golangci.yml
Labels: security

#10357 Docs: Adds clarity to step on shutting down ingesters
  docs/sources/mimir/configure/configure-spread-minimizing-tokens/index.md
Labels: type/docs

#10375 ruler: cap the number of remote eval retries
  CHANGELOG.md
  cmd/mimir/config-descriptor.json
  cmd/mimir/help-all.txt.tmpl
  cmd/mimir/help.txt.tmpl
  docs/sources/mimir/configure/configuration-parameters/index.md
  pkg/mimir/modules.go
  pkg/ruler/remotequerier.go
  pkg/ruler/remotequerier_test.go
Labels: component/ruler

#10393 ruler: use max_retries_rate flag
  pkg/mimir/modules.go
Labels: backport r316, backport r324

#9795 MQE: Add support for delta function
  pkg/streamingpromql/engine_test.go
  pkg/streamingpromql/functions.go
  pkg/streamingpromql/operators/functions/rate_increase.go
  pkg/streamingpromql/testdata/ours/functions.test
  pkg/streamingpromql/testdata/upstream/functions.test
Labels: release/notified-changelog-cut

#10403 ruler: increase retries backoff limit to 1m
  CHANGELOG.md
  pkg/ruler/remotequerier.go
Labels: backport r316, backport r321, backport r324, backport r320

#10470 alertmanager: Sync metric documentation from upstream
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_metrics.go
  pkg/alertmanager/alertmanager_metrics_test.go
Labels: component/alertmanager
