Repository grafana/mimir, pull requests merged in 2025-05, with the labels that each got.

#10816 ruler: Make alertmanager client and all related config per-tenant configurable
  CHANGELOG.md
  cmd/mimir/config-descriptor.json
  docs/sources/mimir/configure/configuration-parameters/index.md
  operations/compare-helm-with-jsonnet/components/config/irrelevant-config.yaml
  pkg/mimir/modules.go
  pkg/mimir/modules_test.go
  pkg/mimir/runtime_config.go
  pkg/ruler/compat.go
  pkg/ruler/manager.go
  pkg/ruler/manager_test.go
  pkg/ruler/notifier.go
  pkg/ruler/notifier/notifier_config.go
  pkg/ruler/notifier/notifier_config_test.go
  pkg/ruler/notifier_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_mock.go
  pkg/util/validation/limits_test.go
  tools/doc-generator/parse/parser.go
Labels: release/notified-changelog-cut

#11366 Remove experimental flag for native histograms
  docs/sources/mimir/configure/configure-native-histograms-ingestion.md
  docs/sources/mimir/send/native-histograms/_index.md
  docs/sources/mimir/visualize/native-histograms/_index.md
Labels: type/docs

#11396 Improve MimirIngestedDataTooFarInTheFuture runbook with more details
  docs/sources/mimir/manage/mimir-runbooks/_index.md
Labels: enhancement, monitoring/runbooks

#11413 Alerts: Enrich alerts for invalid cluster validation labels
  CHANGELOG.md
  operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
  operations/mimir-mixin-compiled-baremetal/alerts.yaml
  operations/mimir-mixin-compiled-gem/alerts.yaml
  operations/mimir-mixin-compiled/alerts.yaml
  operations/mimir-mixin/alerts/alerts.libsonnet
Labels: enhancement, monitoring/alerts

#11425 Upgrade to dskit@10bc270c967b
  go.mod
  go.sum
  vendor/github.com/grafana/dskit/middleware/http_cluster.go
  vendor/github.com/grafana/dskit/spanlogger/spanlogger.go
  vendor/modules.txt
Labels: chore, backport r341

#11447 Use Mimir fork of prometheus/otlptranslator
  go.mod
  go.sum
  vendor/modules.txt
Labels: chore

#11471 Upgrade mimir-prometheus
  go.mod
  go.sum
  vendor/github.com/prometheus/prometheus/model/labels/labels.go
  vendor/github.com/prometheus/prometheus/model/labels/labels_stringlabels.go
  vendor/github.com/prometheus/prometheus/model/labels/sharding.go
  vendor/github.com/prometheus/prometheus/model/labels/sharding_stringlabels.go
  vendor/modules.txt
Labels: backport r343

#11429 Distributor: simplify code for validateSeries
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
Labels: chore, component/distributor

#11495 ruler: handle gRPC status error from when tenant has rules disabled
  CHANGELOG.md
  pkg/ruler/api.go
Labels: backport r341, backport r343, backport r342

#11505 Revert "Query-frontend: Avoid some re-parsing of PromQL (#11437)"
  CHANGELOG.md
  pkg/frontend/querymiddleware/codec.go
  pkg/frontend/querymiddleware/experimental_functions.go
  pkg/frontend/querymiddleware/model_extra.go
  pkg/frontend/querymiddleware/prune.go
  pkg/frontend/querymiddleware/querysharding.go
  pkg/frontend/querymiddleware/remote_read.go
  pkg/frontend/querymiddleware/results_cache.go
  pkg/frontend/querymiddleware/spin_off_subqueries.go
  pkg/frontend/querymiddleware/split_and_cache.go
  pkg/frontend/querymiddleware/split_and_cache_test.go
  pkg/frontend/querymiddleware/split_by_instant_interval.go
  pkg/frontend/querymiddleware/stats.go
Labels: backport r343

#11509 Update alerting module to 92adaaa0147
  go.mod
  go.sum
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/log.go
  pkg/alertmanager/log_test.go
  pkg/alertmanager/sender_test.go
  vendor/github.com/grafana/alerting/definition/alertmanager.go
  vendor/github.com/grafana/alerting/definition/merge.go
  vendor/github.com/grafana/alerting/http/client.go
  vendor/github.com/grafana/alerting/http/webhook.go
  vendor/github.com/grafana/alerting/images/images.go
  vendor/github.com/grafana/alerting/images/providers.go
  vendor/github.com/grafana/alerting/images/testing.go
  vendor/github.com/grafana/alerting/images/utils.go
  vendor/github.com/grafana/alerting/logging/log.go
  vendor/github.com/grafana/alerting/notify/factory.go
  vendor/github.com/grafana/alerting/notify/grafana_alertmanager.go
  vendor/github.com/grafana/alerting/notify/receivers.go
  vendor/github.com/grafana/alerting/receivers/alertmanager/alertmanager.go
  vendor/github.com/grafana/alerting/receivers/base.go
  vendor/github.com/grafana/alerting/receivers/dinding/dingding.go
  vendor/github.com/grafana/alerting/receivers/discord/discord.go
  vendor/github.com/grafana/alerting/receivers/email/email.go
  vendor/github.com/grafana/alerting/receivers/email_sender.go
  vendor/github.com/grafana/alerting/receivers/googlechat/googlechat.go
  vendor/github.com/grafana/alerting/receivers/jira/jira.go
  vendor/github.com/grafana/alerting/receivers/kafka/kafka.go
  vendor/github.com/grafana/alerting/receivers/line/line.go
  vendor/github.com/grafana/alerting/receivers/mqtt/mqtt.go
  vendor/github.com/grafana/alerting/receivers/oncall/oncall.go
  vendor/github.com/grafana/alerting/receivers/opsgenie/opsgenie.go
  vendor/github.com/grafana/alerting/receivers/pagerduty/pagerduty.go
  vendor/github.com/grafana/alerting/receivers/pushover/pushover.go
  vendor/github.com/grafana/alerting/receivers/sensugo/sensugo.go
  vendor/github.com/grafana/alerting/receivers/slack/slack.go
  vendor/github.com/grafana/alerting/receivers/sns/sns.go
  vendor/github.com/grafana/alerting/receivers/teams/teams.go
  vendor/github.com/grafana/alerting/receivers/telegram/telegram.go
  vendor/github.com/grafana/alerting/receivers/testing.go
  vendor/github.com/grafana/alerting/receivers/threema/threema.go
  vendor/github.com/grafana/alerting/receivers/util.go
  vendor/github.com/grafana/alerting/receivers/victorops/victorops.go
  vendor/github.com/grafana/alerting/receivers/webex/webex.go
  vendor/github.com/grafana/alerting/receivers/webhook.go
  vendor/github.com/grafana/alerting/receivers/webhook/webhook.go
  vendor/github.com/grafana/alerting/receivers/wecom/wecom.go
  vendor/github.com/grafana/alerting/templates/template_data.go
  vendor/modules.txt
Labels: component/alertmanager

#11530 [release-2.15] Upgrade Alpine Linux in Dockerfiles to 3.20.6
  CHANGELOG.md
  cmd/metaconvert/Dockerfile
  cmd/mimir/Dockerfile.alpine
  cmd/mimir/Dockerfile.continuous-test
  cmd/mimirtool/Dockerfile
  cmd/query-tee/Dockerfile
  development/mimir-ingest-storage/dev.dockerfile
  development/mimir-microservices-mode/dev.dockerfile
  development/mimir-monolithic-mode-with-swift-storage/dev.dockerfile
  development/mimir-monolithic-mode/dev.dockerfile
  development/mimir-read-write-mode/dev.dockerfile
  tools/copyblocks/Dockerfile
Labels: security, area/build

#11555 [r339] Upgrade to dskit@26335405716d (#11549)
  CHANGELOG.md
  go.mod
  go.sum
  pkg/frontend/frontend_test.go
  vendor/github.com/grafana/dskit/middleware/http_cluster.go
  vendor/modules.txt
Labels: backport

#11559 [r341] Upgrade to dskit@18b79c4e9e07 (#11549)
  CHANGELOG.md
  go.mod
  go.sum
  pkg/frontend/frontend_test.go
  vendor/github.com/grafana/dskit/middleware/http_cluster.go
  vendor/modules.txt
Labels: backport

#11561 [r344] Upgrade to dskit@f84dc58e0bd9 (#11549)
  CHANGELOG.md
  go.mod
  go.sum
  pkg/frontend/frontend_test.go
  vendor/github.com/grafana/dskit/middleware/http_cluster.go
  vendor/modules.txt
Labels: backport

#11560 [r343] Upgrade to dskit@4976ce2fd93c (#11549)
  CHANGELOG.md
  go.mod
  go.sum
  pkg/frontend/frontend_test.go
  vendor/github.com/grafana/dskit/middleware/http_cluster.go
  vendor/modules.txt
Labels: backport

#11335 adds use cases for mimir dashboards
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/alertmanager-resources/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/alertmanager/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/compactor-resources/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/compactor/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/config/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/object-store/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/overrides/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/overview-networking/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/overview-resources/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/overview/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/queries/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/reads-networking/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/reads-resources/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/reads/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/remote-ruler-reads-networking/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/remote-ruler-reads-resources/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/remote-ruler-reads/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/rollout-progress/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/ruler/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/scaling/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/slow-queries/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/tenants/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/top-tenants/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/writes-networking/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/writes-resources/index.md
  docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/writes/index.md
Labels: type/docs

#11537 [release-2.15] Build: Upgrade to Go v1.23.9
  CHANGELOG.md
  Makefile
  mimir-build-image/Dockerfile
Labels: security, area/build
